package robowars.shared.model;

public enum CommandType {
	
	MOVE_CONTINUOUS, TURN_RIGHT_ANGLE_LEFT, TURN_RIGHT_ANGLE_RIGHT, STOP,
	MOVE_DEGREE_TURN, MOVE_COORDINATE, FIRE_PROJECTILE, RETURN_TO_START_POSITION,
	SET_POSITION, EXIT;
	
}
