package robowars.shared.model;

public enum CommandType {
	MOVE_CONTINUOUS, TURN_ANGLE_LEFT, TURN_ANGLE_RIGHT, STOP, ROLLING_TURN,
	MOVE_COORDINATE, FIRE_PROJECTILE, RETURN_TO_START_POSITION,
	SET_POSITION, EXIT;
}
