package robowars.server.controller;

import java.util.EventObject;

/**
 * Base class of all events generated by ServerLobby. This includes events
 * indicating that a player or robot has left the game, a player has changed
 * their ready / spectator state, a player has sent a chat message, or a game 
 * has been launched or terminated.
 */
public abstract class ServerLobbyEvent extends EventObject {
	
	/** Constants defining event type */
	public static final int EVENT_PLAYER_JOINED = 0;
	public static final int EVENT_PLAYER_LEFT = 1;
	public static final int EVENT_CHAT_MESSAGE = 2;
	public static final int EVENT_ROBOT_REGISTERED = 3;
	public static final int EVENT_ROBOT_UNREGISTERED = 4;
	public static final int EVENT_PLAYER_STATE_CHANGE = 5;
	public static final int EVENT_GAME_LAUNCH = 6;
	public static final int EVENT_GAME_OVER = 7;
	public static final int EVENT_GAMETYPE_CHANGE = 8;
	
	/** The type of event (using constants defined in ServerLobbyEvent) */
	private int type;
	
	/**
	 * Constructs a new ServerLobbyEvent (abstract class - only used for subclasses)
	 * @param lobby	The ServerLobby that generated the event
	 * @param type	The type of event (constants defined in ServerLobbyEvent)
	 */
	public ServerLobbyEvent(ServerLobby lobby, int type) {
		super(lobby);
		this.type = type;
	}
	
	/**
	 * @return	The type of the event
	 */
	public int getEventType() {
		return type;
	}
	
	/**
	 * TODO: Should be replaced with a more efficient data type than string at
	 * 		 some point
	 * @return	A string representation of the event which can be sent over
	 * 			a network to connected clients.
	 */
	public abstract String serialize();
}